server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
#  server:
#    enable-self-preservation: false
#  instance:
#     leaseRenewalIntervalInSeconds: 1
#     leaseExpirationDurationInSeconds: 2
#  server:
#    eviction-interval-timer-in-ms: 1000

spring:
  cloud:
    config:
      uri: http://localhost:8081


# spring.cloud.config.username=root
# spring.cloud.config.password=s3cr3t
# spring.cloud.config.name=conf
# spring.cloud.config.uri=http://localhost:8081